### login de usuario
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "profesor",
    "password": "hash_falso_123"
}

### consultar todas las peliculas
GET http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTg2NjcyNCwiZXhwIjoxNzc1OTAyNzI0fQ.X_2w69yB5BVtg3DHQiEpLvIXJl7wdVx3rqcw8_fq0jY

### consultar una pelicula por id
GET http://localhost:3000/movies/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTg2NjcyNCwiZXhwIjoxNzc1OTAyNzI0fQ.X_2w69yB5BVtg3DHQiEpLvIXJl7wdVx3rqcw8_fq0jY

### crear pelicula
POST http://localhost:3000/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTg2NjcyNCwiZXhwIjoxNzc1OTAyNzI0fQ.X_2w69yB5BVtg3DHQiEpLvIXJl7wdVx3rqcw8_fq0jY

{
    "title": "The Matrix Recargado",
    "release_year": 2003,
    "synopsis": "Neo continua su lucha contra las maquinas.",
    "director": [3, 4],
    "posterUrl": "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
    "genre": [1, 2]
}

### actualizar pelicula
PUT http://localhost:3000/movies/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTg2NjcyNCwiZXhwIjoxNzc1OTAyNzI0fQ.X_2w69yB5BVtg3DHQiEpLvIXJl7wdVx3rqcw8_fq0jY

{
    "title": "The Matrix Reloaded"
}

### obtener todos los directores
GET http://localhost:3000/directors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTg2NjcyNCwiZXhwIjoxNzc1OTAyNzI0fQ.X_2w69yB5BVtg3DHQiEpLvIXJl7wdVx3rqcw8_fq0jY

### agregar director
POST http://localhost:3000/directors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTg2NjcyNCwiZXhwIjoxNzc1OTAyNzI0fQ.X_2w69yB5BVtg3DHQiEpLvIXJl7wdVx3rqcw8_fq0jY

{
    "full_name": "Mel Gibson"
}

### eliminar pelicula
DELETE http://localhost:3000/movies/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTg2NjcyNCwiZXhwIjoxNzc1OTAyNzI0fQ.X_2w69yB5BVtg3DHQiEpLvIXJl7wdVx3rqcw8_fq0jY
